Added my group to the groups.yaml file
uob-sepp/groups-2024 pull request #122
Opened 2024-11-27 09:00 UTC by joshandetc

Added my group to the groups.yaml file page

2024-11-27 20:46 UTC, mbg requested changes

2024-11-27 20:46 UTC, mbg commented on config/groups.yaml
> +- members:
This isn't right: each `-` denotes an item in a list, so you have added two items here, but both `name` and `members` are supposed to be part of the same item in the list. 

```suggestion
  members:
```

2024-11-27 20:46 UTC, mbg commented on config/groups.yaml
> +    - "2885512"
Just to check, are you happy to have only two members in your group? The normal minimum is 3, but I am happy with this if you are.

2024-11-29 15:59 UTC, joshandetc commented
Hi Michael,

Sorry for the late response but are you able to add me to another group? The members in this group are very unresponsive so I'm finding it hard to start the prototype assignment.

Thanks,
Josh

________________________________
From: Michael B. Gale ***@***.***>
Sent: Wednesday, 27 November 2024 8:46 PM
To: uob-sepp/groups-2024 ***@***.***>
Cc: Joshua Fernando (UG Aff Comp Sci/S'ware Eng FT) ***@***.***>; Author ***@***.***>
Subject: Re: [uob-sepp/groups-2024] Added my group to the groups.yaml file (PR #122)

CAUTION: This email originated from outside the organisation. Do not click links or open attachments unless you recognise the sender and know the content is safe.


@mbg requested changes on this pull request.

________________________________

In config/groups.yaml<https://github.com/uob-sepp/groups-2024/pull/122#discussion_r1861228483>:

> @@ -639,3 +639,7 @@
     - "2575138"
     - "2522944"
   id: 190041
+- name: "Group LuNiJo"
+- members:


This isn't right: each - denotes an item in a list, so you have added two items here, but both name and members are supposed to be part of the same item in the list.

⬇️ Suggested change

-- members:
+  members:


________________________________

In config/groups.yaml<https://github.com/uob-sepp/groups-2024/pull/122#discussion_r1861229143>:

> +    - "2879998"
+    - "2885512"


Just to check, are you happy to have only two members in your group? The normal minimum is 3, but I am happy with this if you are.

—
Reply to this email directly, view it on GitHub<https://github.com/uob-sepp/groups-2024/pull/122#pullrequestreview-2465926011>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BNGGERB6ZAEMRXWU5XANADL2CYVUHAVCNFSM6AAAAABSSJ7J3SVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDINRVHEZDMMBRGE>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-11-29 18:02 UTC, mbg commented
Superseded by #131

2024-11-29 18:02 UTC, closed without merging