adding group
uob-sepp/groups-2024 pull request #85
Opened 2024-11-24 16:04 UTC by kevvin2

2024-11-24 16:34 UTC, mbg requested changes

2024-11-24 16:34 UTC, mbg commented on config/groups.yaml
> +    - "2629286"
This isn't valid YAML, it would need to be:
```suggestion
- name: "SEPP Assignment Group"
  members:
    - "2629286"
```

2024-11-24 22:46 UTC, mbg requested changes
It looks like `2629286` is already in a group `SEPP Assignment Prototype` (which I think was imported from the self sign-up groups). You have two options:

1. Instead of adding a new group, add the extra members to the existing group (the one with id `190011`)
1. Remove the existing group from `groups.yaml`

2024-11-25 16:03 UTC, mbg commented
> But I don't have the option to push the changes? 

You should be able to push anything you want to your branch. In the [Files changed tab](https://github.com/uob-sepp/groups-2024/pull/85/files), which shows the cumulative changes of your PR, it does look like you have added the members to the existing group, but the new group is also still there.

2024-11-25 16:22 UTC, kevvin2 commented
Sorry I meant merge to the original repo from my fork by 'push'. I deleted the old group now, which did not have an id, and left the new group with an id with the added members from my last commit, is it now correct?

2024-11-25 18:02 UTC, mbg approved these changes

2024-11-25 18:02 UTC, merged