Added new group WomenInMenFields
uob-sepp/groups-2024 pull request #94
Opened 2024-11-25 11:27 UTC by tchippy

2024-11-25 20:50 UTC, mbg requested changes
It looks like `2438550` isn't a student on the course. Maybe there's a typo in the ID?

2024-11-27 00:10 UTC, tchippy commented
changed id

2024-11-27 20:02 UTC, mbg requested changes

2024-11-27 20:02 UTC, mbg commented on config/groups.yaml
> +  members :
This looks unintentional and shouldn't be part of this PR

2024-11-28 14:40 UTC, merged